# creating project using  github actions 

name: creating project using github actions 

on :
    push:
        branches: [master] 
    pull_request:
        branches: [master]


jobs:
    build:
        runs-on: ubuntu-latest
        permissions: 
            contents: read

        
        steps:
         - uses: actions/checkout@v1
           name: set up java sdk  
         - uses: actions/setup@18
           with:
            java-version: 17
         
         - name: providing permissions 
           run: chmod +x javasdk17

         - name: to run the java 
           run: ./gradlew
